name: Generate FHR Device Audit Report

on:
  workflow_dispatch: {}
  schedule:
    # 06:00 America/Los_Angeles = 13:00 UTC (adjust to taste)
    - cron: "0 13 * * 1-5"

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt

      - name: Create env file for ServiceNow
        run: |
          mkdir -p scripts
          cat > scripts/servicenow.env <<EOF  
          SERVICENOW_INSTANCE=${{ secrets.SERVICENOW_INSTANCE }}
          SERVICENOW_USER=${{ secrets.SERVICENOW_USER }}
          SERVICENOW_PASS=${{ secrets.SERVICENOW_PASS }}
          EOF

      - name: Run report
        env:
          OUTPUT_DIR: output
          MPLBACKEND: Agg
        run: |
          mkdir -p output
          python scripts/get_servicenow_data.py
          

      # A) Downloadable artifact
      - uses: actions/upload-artifact@v4
        with:
          name: fhr-computer-request
          path: output/fhr_computer_request.xlsx
          if-no-files-found: error

      # B) Commit latest file back to repo (keep a single static filename)
      - name: Commit results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add output/fhr_computer_request.xlsx
          git commit -m "chore: update report [skip ci]" || echo "No changes to commit"
          git push
